
all:
	pdflatex 3DPhoto_Proposal_Grundmann_Schneuwly_Oswald 
	bibtex 3DPhoto_Proposal_Grundmann_Schneuwly_Oswald
	pdflatex 3DPhoto_Proposal_Grundmann_Schneuwly_Oswald
	pdflatex 3DPhoto_Proposal_Grundmann_Schneuwly_Oswald 

clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *.blg *.pfg *.out)
